mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.lidhk.model


#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

spring:
  profiles:
    active: dev
  redis:
  ##Redis数据库索引（默认0）
    database: 0
    host: 192.168.8.117
    port: 6379
    jedis:
      pool:
        ###连接池最大连接数（使用负值表示没影响）
        max-active: 8
        ###连接池最大阻塞等待时间（使用负值表示没影响）
        max-wait: -1
        ###连接池最大空闲连接
        max-idle: 5
        ###连接池最小空闲连接
        min-idle: 0
    timeout: 1000
    password:
  rabbitmq:
    host: 192.168.8.117
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
    constomers: 5
    max-constomers: 20
logging:
  config: classpath:logback-spring.xml




