mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.lidhk.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

spring:
  profiles:
    active: @activatedProperties@
logging:
  config: classpath:logback-spring.xml




